---
name: Build disk images

on:
  workflow_dispatch:
    inputs:
      platform:
        required: true
        type: choice
        options:
          - amd64
          - arm64

env:
  IMAGE_NAME: ${{ github.event.repository.name }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  DEFAULT_TAG: latest

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build disk images
    runs-on: ${{ inputs.platform == 'amd64' && 'ubuntu-24.04' || 'ubuntu-24.04-arm' }}
    permissions:
      contents: read
      packages: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build QCOW2
        uses: ublue-os/titanoboa@main
        with:
          image: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
          output: qcow2
          platform: ${{ inputs.platform }}
          hook-pre-initramfs: ${{ github.workspace }}/iso_files/pre_initramfs.sh

      - name: Build ISO
        uses: ublue-os/titanoboa@main
        with:
          image: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
          output: anaconda-iso
          platform: ${{ inputs.platform }}
          hook-pre-initramfs: ${{ github.workspace }}/iso_files/pre_initramfs.sh
