---
name: Build disk images

on:
  workflow_dispatch:
    inputs:
      platform:
        required: true
        type: choice
        options:
          - amd64
          - arm64

jobs:
  build-iso:
    name: Build ISO
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: read
      id-token: write

    steps:
      - name: Prepare environment
        run: |
          echo "IMAGE_REF=ghcr.io/sinclair95/reikon-v1:latest" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v6

      - name: Build ISO
        id: build_iso
        uses: ublue-os/titanoboa@main
        with:
          image-ref: ${{ env.IMAGE_REF }}
          livesys: true
          add-polkit: true
          hook-pre-initramfs: ${{ github.workspace }}/iso_files/pre_initramfs.sh
          iso-dest: ${{ github.workspace }}/output.iso
          builder-distro: fedora

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: reikon-iso
          path: ${{ steps.build_iso.outputs.iso-dest }}
          if-no-files-found: error
