---
name: Build disk images

on:
  workflow_dispatch:
    inputs:
      platform:
        required: true
        type: choice
        options:
          - amd64
          - arm64

jobs:
  build-iso:
    name: Build ISO
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build ISO
        uses: ublue-os/titanoboa@main
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
          livesys: true
          add-polkit: true
          hook-pre-initramfs: ${{ github.workspace }}/iso_files/pre_initramfs.sh
          iso-dest: .
          builder-distro: fedora
